:sparkles: :construction: (feature/totalCV) #131 내용 적용
ILGOB/It-sME pull request #144
Opened 2023-03-13 07:56 UTC by blooper20

## 변경점 설명

- categoryEditViewController에 #131 코드 적용
- 아직 데이터 처리 미구현

## 참고 자료

<img src=https://user-images.githubusercontent.com/70786167/224639476-eaf10943-44a0-49f7-88be-66293e55d97c.png width="250"/>
<img src=https://user-images.githubusercontent.com/70786167/224639765-0a3124e5-c27d-411f-addc-8cd6dd1d27c4.png width="250"/>

## PR Checklist

- [ ] 변경 사항을 적용하고 빌드&테스트 실행을 해봤나요?

2023-03-13 08:32 UTC, woin2ee requested changes
오타 수정과 궁금한 부분 한 번 확인 부탁드립니다~

2023-03-13 08:32 UTC, woin2ee commented on ItsME/Presentation/Common/Cells/TextViewCell.swift
> +    var textViewHeigt = 100
오타있습니다!
`textViewHeight`

2023-03-13 08:32 UTC, woin2ee commented on ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryEditing/CategoryEditingViewController.swift
> +        $0.textViewHeigt = 200
혹시 여기서 높이를 200으로 설정하면 실제 View 에도 높이가 적용이 되나요? 제 예상으로는 높이 적용이 안될것같아서 확인하고싶습니다.

2023-03-14 04:08 UTC, blooper20 commented on ItsME/Presentation/Common/Cells/TextViewCell.swift
> +    var textViewHeigt = 100
이런...
고치겠습니다.

2023-03-14 04:22 UTC, blooper20 commented on ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryEditing/CategoryEditingViewController.swift
> +        $0.textViewHeigt = 200
여기서 높이를 200으로 설정한다고 바뀌지 않은걸 체크하지 못했네요 의도하던 방향으로 다시 커밋하겠습니다.

2023-03-14 05:16 UTC, merged