:sparkles: :construction: (feature/totalCV) 카테고리테이블의 헤더뷰에 기능 추가
ILGOB/It-sME pull request #151
Opened 2023-03-17 08:07 UTC by blooper20

## 변경점 설명

- 추가버튼(추후에 CategoryEditingViewController가 뜨게끔 구현)
- 섹션 편집 기능(UILabel을 TextField로 바꿔 EditMode일 때만 편집이 가능하게끔 구현)
- 키보드의 엔터 부분을 return으로 변경 후 눌렀을 때 키보드가 내려가게 끔 구현
## 참고 자료

<img src="https://user-images.githubusercontent.com/70786167/225847370-4ba8cd5e-816f-4ca0-84da-75008971c46e.png" width = "300">
<img src="https://user-images.githubusercontent.com/70786167/225847445-6457f200-850f-4c1b-8034-934df4b6f22e.png" width = "300">

## PR Checklist

- [ ] 변경 사항을 적용하고 빌드&테스트 실행을 해봤나요?

2023-03-17 08:52 UTC, woin2ee requested changes

2023-03-17 08:52 UTC, woin2ee commented on ItsME/Presentation/Common/TableSection/CategoryHeaderView.swift
> +            headerContentView.layer.cornerRadius = 10
if 문과 연관이 없는 코드는 if 문 블록 외부에 작성하는게 가독성면에서 좋습니다. (if 문이 너무 길어서 읽기 힘들어요ㅠㅠ)

2023-03-17 08:52 UTC, woin2ee commented on ItsME/Presentation/Common/TableSection/CategoryHeaderView.swift
> +            titleTextField.clearsOnBeginEditing = false
위와 같습니다.

2023-03-20 13:43 UTC, blooper20 commented on ItsME/Presentation/Common/TableSection/CategoryHeaderView.swift
> +            headerContentView.layer.cornerRadius = 10
함수화하여서 밖으로 빼서 작성하라는 건가요?
changeBoardView() 처럼??

2023-03-20 13:47 UTC, blooper20 commented on ItsME/Presentation/Common/TableSection/CategoryHeaderView.swift
> +            }
코드를 수정하면서 작성하다보니 이런 실수가 있었네요
 수정하겠습니다!!

2023-03-20 14:25 UTC, blooper20 commented on ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
> +            self.categoryTableView.reloadData() // 변경된 데이터를 다시 로드
이것도 이것저것 적용해가면서 마지막에 확인을 제대로 못해서 올라간것 같습니다
수정하겠습니다 ㅠㅜ

2023-03-20 14:43 UTC, blooper20 commented on ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
> +    var isEditingMode: Bool = false
이 또한 정신없이 이것저것 시도하다가 그대로 PR에 담긴거 같습니다.
수정해서 다시 보내겠습니다

2023-03-21 04:00 UTC, woin2ee commented on ItsME/Presentation/Common/TableSection/CategoryHeaderView.swift
> +            headerContentView.layer.cornerRadius = 10
앗 이게 58번 라인을 말한거였는데 리뷰를 다니까 위 3개라인도 같이 표기돼서 혼란이 있었네요. 58번 라인만 해당됩니다.
`headerContentView.layer.cornerRadius = 10` 코드는 editingMode 와 연관이 없기 때문에 블록 외부(ex: 초기화 블록)에 작성하면 좋다는 의미였습니다.

2023-03-21 04:01 UTC, woin2ee commented on ItsME/Presentation/Common/TableSection/CategoryHeaderView.swift
> +            titleTextField.returnKeyType = .done
62번 라인만 해당됩니다.

2023-03-21 04:01 UTC, woin2ee commented on ItsME/Presentation/Common/TableSection/CategoryHeaderView.swift
> +            titleTextField.clearsOnBeginEditing = false
89번 라인만 해당됩니다.

2023-03-21 04:42 UTC, woin2ee approved these changes
확인했습니다.

2023-03-21 04:42 UTC, merged