:bug: :construction: (feature/HomeView) #42 번 이슈에 관한 오류 해결
ILGOB/It-sME pull request #45
Opened 2022-12-12 09:12 UTC by blooper20

## 변경점 설명

- 다른 뷰로 넘어갔다 올 때 계속 StackView에 같은 정보가 쌓이는 에러 해결

## 참고 자료

![ezgif com-gif-maker](https://user-images.githubusercontent.com/70786167/207006244-2b03d915-75ee-4c0c-842a-6a65ef857c95.gif)

## PR Checklist

- [x] 변경 사항을 적용하고 빌드&테스트 실행을 해봤나요?

2022-12-12 11:44 UTC, woin2ee requested changes

2022-12-12 11:44 UTC, woin2ee commented on ItsME/Presentation/Scenes/Home/HomeViewController.swift
> +            if self.vStackLayout.arrangedSubviews.isEmpty{
```suggestion
            if self.vStackLayout.arrangedSubviews.isEmpty {
```
아래 if문 처럼 space를 줬습니다.

2022-12-12 11:53 UTC, woin2ee commented
if 문으로 subviews 가 비어있을때만 레이아웃을 설정해주면 개수가 0->X개일때는 제대로 동작하지만, 2->3개로 달라졌을때는 레이아웃이 설정이 안될것으로 보임.
아마 새로 데이터가 올때마다 기존의 subviews 를 삭제하고 새로 온 데이터에 맞게 Components 를 생성해서 지정해줘야 할듯

2022-12-13 06:31 UTC, blooper20 commented
> if 문으로 subviews 가 비어있을때만 레이아웃을 설정해주면 개수가 0->X개일때는 제대로 동작하지만, 2->3개로 달라졌을때는 레이아웃 설정이 안될것으로 보임. 아마 새로 데이터가 올때마다 기존의 subviews 를 삭제하고 새로 온 데이터에 맞게 Components 를 생성해서 지정해줘야 할듯

나중에 추가했을 때나 정보가 변경 되었을 때를 얘기하는거죠? 그 생각을 못했었네요

2022-12-13 12:04 UTC, woin2ee approved these changes
확인이요~

2022-12-13 12:05 UTC, merged