Edit profile 화면 구현 작업
ILGOB/It-sME pull request #46
Opened 2022-12-15 07:25 UTC by woin2ee

## 변경점 설명

- 유저 정보에 학력 정보 추가
- 프로필 수정 화면에 UserInfoItems 바인딩
- #44 : 프로필 이미지 비율 조정

## 참고 자료

<img width="400" alt="image" src="https://user-images.githubusercontent.com/81426024/207798487-a78b0c39-99aa-45fa-b11b-f94f44f3382b.png">

## PR Checklist

- [x] 변경 사항을 적용하고 빌드&테스트 실행을 해봤나요?

2022-12-15 07:37 UTC, blooper20 requested changes
각진 것보다는 둥든게 더 이쁠거 같아서 ㅎㅎ

2022-12-16 03:25 UTC, woin2ee commented
> 각진 것보다는 둥든게 더 이쁠거 같아서 ㅎㅎ

혹시 어느 부분 말하는건가욥
UserInfoItems 묶어놓은 박스 말하는거면 디자인쪽 작업은 안한 상태라 임시로 바탕색을 넣어놓은거라...

2022-12-16 03:28 UTC, woin2ee commented
<img width="400" alt="image" src="https://user-images.githubusercontent.com/81426024/208015405-086016f5-a4f2-46dc-8131-7c64da50e946.png">
일단 배경색 제거해서 올렸습니당

2022-12-17 08:17 UTC, blooper20 commented
> > 각진 것보다는 둥든게 더 이쁠거 같아서 ㅎㅎ
> 
> 혹시 어느 부분 말하는건가욥 UserInfoItems 묶어놓은 박스 말하는거면 디자인쪽 작업은 안한 상태라 임시로 바탕색을 넣어놓은거라...

임시면 상관 없겠네용 ㅎㅎ

2022-12-17 08:18 UTC, blooper20 approved these changes
머지하겠습니다~

2022-12-17 08:18 UTC, merged