#80 섹션에 대한 작업 미완
ILGOB/It-sME pull request #85
Opened 2023-02-07 12:15 UTC by blooper20

## 변경점 설명

## 참고 자료

<img width="411" alt="스크린샷 2023-02-07 오후 9 13 18" src="https://user-images.githubusercontent.com/70786167/217241973-0f93d365-f631-447c-bf50-cfb05cf6de99.png">
- 행에 맞는 내용이 오게끔 기능 구현
- 섹션에 대한 내용을 추가해주기만 하면 테이블 완성

## PR Checklist

- [ ] 변경 사항을 적용하고 빌드&테스트 실행을 해봤나요?

2023-02-10 10:28 UTC, woin2ee requested changes

2023-02-10 10:28 UTC, woin2ee commented on ItsME/Repositories/CVRepository.swift
> +                let jsonData = try JSONSerialization.data(withJSONObject: dataSnapshot.value as Any)
이 부분 코드는 왜 다시 롤백한건지 이유가 있을까요?

2023-02-10 10:28 UTC, woin2ee commented on ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
> +    var resumeCategoryBinding: Binder<[ResumeCategory]> {
혹시 이 부분 사용하지 않는 코드로 저번에 삭제했던 부분 아닌가요?

2023-02-13 06:56 UTC, blooper20 reviewed
중간에 이미 커밋해놓은 작업이 있어서 먼저 머지해주시면 리뷰내용 토대로 변경하여 같이 PR 보내겠습니다

2023-02-13 06:56 UTC, blooper20 commented on ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
> +    var resumeCategoryBinding: Binder<[ResumeCategory]> {
혹시 사용할 일 있을까봐 그대로 두었었는데 다시 고민해보니 필요 없는것 같아서 지우겠습니다!

2023-02-13 06:56 UTC, blooper20 commented on ItsME/Repositories/CVRepository.swift
> +                let jsonData = try JSONSerialization.data(withJSONObject: dataSnapshot.value as Any)
오류가 자꾸 나서 새롭게 하려고 pull 받고 다시 하는 작업중에 이 부분의 변경사항이 빠졌던거 같습니다 
다시 고치겠습니다

2023-02-13 10:36 UTC, woin2ee commented
> 중간에 이미 커밋해놓은 작업이 있어서 먼저 머지해주시면 리뷰내용 토대로 변경하여 같이 PR 보내겠습니다

넵 확인했습니다.

2023-02-13 10:36 UTC, woin2ee approved these changes

2023-02-13 10:36 UTC, merged